### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by NikolaiT** [NikolaiT/se-scraper#38]
![image](https://user-images.githubusercontent.com/4533323/61479635-87328600-a994-11e9-8f7b-b1b9f6d26f63.png)

I need help guys, I think I added a couple of vulns :/

**Comment by victor9000** [comment]
@NikolaiT I just did a fresh install and wasn't able to recreate the warnings that you encountered.  Perhaps this was addressed in puppeteer@1.19.0?
```
$ npm install se-scraper

> puppeteer@1.19.0 install ./se-test/node_modules/puppeteer
> node install.js

Downloading Chromium r674921 - 112.6 Mb [====================] 100% 0.0s 
Chromium downloaded to ./se-test/node_modules/puppeteer/.local-chromium/linux-674921
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN se-test@1.0.0 No description
npm WARN se-test@1.0.0 No repository field.

+ se-scraper@1.4.1
added 123 packages from 107 contributors and audited 198 packages in 12.722s
found 0 vulnerabilities

$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 198 scanned packages 
```

**Comment by HugoPoi** [comment]
Because there is a `package-lock.json` this behaviour is expected. We just need to do `npm update` some times to ensure dependencies are updated and tested in our local git repository of the project.

package-lock.json is helpful to reproduce the exact dependency tree for reproducing and debugging issues with dependencies. (It is not present in the npm registry package).

More details [here](https://github.com/npm/cli/blob/latest/doc/cli/npm-update.md).

I think we can close this :smiley:

**Comment by NikolaiT** [comment]
:D that was a joke my dear friends
